name: client_app
description: "An app client for the WestCambios service."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  google_nav_bar: ^5.0.7
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  fl_chart: ^1.1.1
  flutter_secure_storage: ^10.0.0
  workmanager: ^0.9.0+3
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
